title: Biostat 823
subtitle: Homework
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site for a Jekyll theme version of
  HTML5 UP's sleek, responsive site template prologue.
author: Jiajie Shen
email: jiajie.shen@duke.edu
avatar: assets/images/avatar.jpg

# You'll want to customize url and baseurl for your own site:
baseurl: "/jekyll-theme-prologue" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site



linkedin_url: www.linkedin.com/in/jiajieshen





theme: jekyll-theme-prologue
